### ISSUE TITLE
Extension should be disabled on Microsoft Documentation sites

### ISSUE THREAD

**Issue by b-vermes** [grantwinney/generate-links-for-headers-in-chrome#12]
Most of Microsoft Documentation sites like this have their own solution implemented: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom
Altering the headings causes glitches with the original link icon (it is displayed righter and so in front of the text instead of left to it).

**Comment by grantwinney** [comment]
Yeah I disable it on GitHub for a similar reason. I pushed an update to disable it on docs.microsoft.com. If you update to version 1.2.7 it should look okay again.
