### ISSUE TITLE
Extension hides header text

### ISSUE THREAD

**Issue by b-vermes** [grantwinney/generate-links-for-headers-in-chrome#13]
Right after the extension loads, the "Create Great Architecture with Archicad" (#mainVideoTitle) text disappears on this site: https://graphisoft.com/ The text can be highlighted when it is readable.

![chrome_bdJbkc8Mvs](https://user-images.githubusercontent.com/68700721/90656474-a6a87c00-e242-11ea-8421-0a1c8365b474.png)
![chrome_fpRjewXAM1](https://user-images.githubusercontent.com/68700721/90656545-ac9e5d00-e242-11ea-91fb-38ed0c8bb02d.png)

**Comment by grantwinney** [comment]
Thanks for letting me know! Not exactly sure why it was doing that, but since the site doesn't appear to use anchors on their headers anyway (so the extension can't generate links for them), I just disabled the extension for that site. If you update to v 1.2.8 it should show the text again.

**Comment by grantwinney** [comment]
Let me know if you have any other issues with that site or any others.

**Comment by b-vermes** [comment]
Actually the site does use anchors but not for all headers. There is a _mainVideoTitle_ ID on the earlier reported text. And the IDs are there on this page too: https://graphisoft.com/resources-and-support/system-requirements

**Comment by grantwinney** [comment]
I don't have time to look into this at the moment, but I'll reopen it so it doesn't get lost.

**Comment by grantwinney** [comment]
This should be fixed, after they approve it in the store. When it updates, it'll come through as version 1.3.0. It doesn't blend in super well on that site, since the font color is black, but then they apply some kind of background gradient thing on top of it... I couldn't inherit that into the icon itself.

**Comment by b-vermes** [comment]
Works well now, thanks! The new icons are nice.
