### ISSUE TITLE
Anchors are huge

### ISSUE THREAD

**Issue by b-vermes** [grantwinney/generate-links-for-headers-in-chrome#14]
The anchor icons placed by the extension are pretty big on Perforce's site. For example: https://www.perforce.com/products/helix-alm/jira-integration
![image](https://user-images.githubusercontent.com/68700721/96845996-9f276e00-1451-11eb-9b4b-97a81e36594a.png)

**Comment by grantwinney** [comment]
At least you can't miss them! That's pretty obnoxious, lol, I'll have to check out why it's doing that...

**Comment by grantwinney** [comment]
This should be fixed, after they approve it in the store. When it updates, it'll come through as version 1.3.0. Let me know if you run into any problems.

**Comment by b-vermes** [comment]
Works well now, thanks!
