### ISSUE TITLE
last update caused the malfunctioning of some websites 

### ISSUE THREAD

**Issue by hadi4172** [grantwinney/generate-links-for-headers-in-chrome#15]
Hi, the last update on svg to font awesome of the chrome extension caused the malfunctioning of some websites. For exemple, go to https://vostfree.com/animes-vostfr/ with your extension disabled, then reactivate it and reload the page and try to click on an anime. You notice that it doesn't work anymore. I've found other websites that also have problems with the extension, but less serious. (for example fullstream.me which doesn't display some icons well anymore)

**Comment by grantwinney** [comment]
Ugh, fix one thing, break another, lol. 😬

Thanks for the heads up.

**Comment by grantwinney** [comment]
I should've had more coffee before making that last change. Alright, I removed the reference to font awesome and fixed the original svg/styling that was causing a couple other issues. When v 1.3.1 is approved in the store, and your browser updates to use it, everything should be good to go. Let me know if you still have any issues though.

**Comment by hadi4172** [comment]
It's perfect, I just tested the new update and the problem seems to have been fixed :) Thanks a lot!

**Comment by grantwinney** [comment]
Good to hear! Thanks for letting me know.
