### ISSUE TITLE
Video Titles On YouTube Disappear When Ext is Active

### ISSUE THREAD

**Issue by lundeen-bryan** [grantwinney/generate-links-for-headers-in-chrome#16]
Possible Bug:
Browser: Chrome v88
Domain: YouTube

GIVEN user is on YouTube 
AND Extension is active
AND user searched for a title
THEN title does not show next to video results.

The URL (if applicable) pertaining to my problem is:
https://www.youtube.com/results?search_query=flexbox+axis

![image](https://user-images.githubusercontent.com/13512507/110224324-54057900-7e8f-11eb-88f5-015c7a20957e.jpg)

NOTE: this does not seem to happen on the "YouTube: Subscriptions" page or the homepage, only in search results.

**Comment by grantwinney** [comment]
Thanks for all the detail.. especially for including a link where I could see it happening. Not exactly sure what's causing that, but I don't really see an opportunity for using this on YouTube, so I just disabled it on that domain.
